export const Types = {
  ENTERPRISES_REQUEST: 'ENTERPRISES_REQUEST',
  ENTERPRISES_SUCCESS: 'ENTERPRISES_SUCCESS',
  ENTERPRISES_FAILURE: 'ENTERPRISES_FAILURE',

  ENTERPRISE_FILTER_REQUEST: 'ENTERPRISE_FILTER_REQUEST',
  ENTERPRISE_FILTER_SUCCESS: 'ENTERPRISE_FILTER_SUCCESS',
  ENTERPRISE_FILTER_FAILURE: 'ENTERPRISE_FILTER_FAILURE',

  ENTERPRISE_DETAIL_REQUEST: 'ENTERPRISE_DETAIL_REQUEST',
  ENTERPRISE_DETAIL_SUCCESS: 'ENTERPRISE_DETAIL_SUCCESS',
  ENTERPRISE_DETAIL_FAILURE: 'ENTERPRISE_DETAIL_FAILURE',
};
